repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v6.0.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 25.11.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    args: ['--extend-ignore','E203,E501,W503']
- repo: https://github.com/pylint-dev/pylint
  rev: v4.0.2
  hooks:
  - id: pylint
    args: ['--disable', 'W0511,W0718,R0801,R0903,R0914']
    language: system
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
    args: ["--disallow-any-generics", "--disallow-untyped-def", "--follow-imports", "skip", "--ignore-missing-imports", "--disable-error-code", "unused-awaitable"]
    language: system